### PR TITLE
Implement decoding mp3

### PR DESCRIPTION
**Pull request by tomaka**
cc @bendykst

Need to change the library to use crates.io before merging.

### CODE REVIEW

**Comment by tomaka** [comment]
I didn't notice at first, but the example sound stops playing because a `Err(Mad(BufLen))` is triggered.

**Comment by tomaka** [comment]
Hum. Libmad is under GPL, so this code is not legal.

**Comment by emersion** [comment]
Note that it's unclear whether or not linking to libmad is allowed: https://en.wikipedia.org/wiki/GNU_General_Public_License#Libraries

Also, you're not using libmad directly, but `simple-mad` which is [licensed under MIT](https://github.com/bendykst/simple-mad.rs/blob/master/LICENSE).

**Comment by mhsjlw** [comment]
Any word on this?

**Comment by tomaka** [comment]
The inner source code is still GPL: https://github.com/bendykst/simple-mad.rs/blob/master/simplemad_sys/libmad-src/COPYRIGHT

**Comment by est31** [comment]
Can this be closed, now that rodio has mp3 support thanks to minimp3?

**Pull request closed without merging**
